package:
  name: ptgaul
  version: 1.0.4

source:
  path: ./

build:
  number: 0

requirements:
  host:
    - bioconda::minimap2
    - bioconda::seqkit
    - bioconda::seqtk
    - bioconda::assembly-stats
    - bioconda::flye
    - bioconda::python
    - bioconda::biopython

  run:
    - minimap2
    - seqkit
    - seqtk
    - assembly-stats
    - flye
    - python
    - biopython

test:
  commands:
    - ptGAUL.sh -h

about:
  home: https://github.com/Bean061/ptgaul
  license: MIT
  license_file: LICENSE
  summary: 'Plastid Genome Assembly Using long-read data (ptGAUL)'
  
extra:
  recipe-maintainers:
    # GitHub IDs for maintainers of the recipe.
    # Always check with the people listed below if they are OK becoming maintainers of the recipe. (There will be spam!)
    - LisaSimpson
    - LandoCalrissian
