package:
  name: ptgaul
  version: 1.0.4

source:
  path: ../src

build:
  number: 0

requirements:
  host:
    - minimap2
    - seqkit
    - seqtk
    - assembly-stats
    - flye
    - python >=3.6
    - biopython

  run:
    - minimap2
    - seqkit
    - seqtk
    - assembly-stats
    - flye
    - python >=3.6
    - biopython

test:
  commands:
    - ptGAUL.sh -h

about:
  home: https://github.com/Bean061/ptgaul
  license: MIT

